version: '3.8'

services:
  jekyll:
    build: .
    ports:
      - "4001:4000"
    volumes:
      - .:/site
      - /site/vendor
      - /site/.bundle
    environment:
      - JEKYLL_ENV=development 